run-name: ${{ github.actor }} is running Unit Tests
on:
  push:
    branches:
      - main
      - feature/*
#  pull_request:
#    branches:
#      - develop

permissions:
  contents: write

jobs:
  run-unit-tests:
    uses: mage-os/infrastructure/.github/workflows/unit-tests.yml@main
