run-name: ${{ github.actor }} is running Unit Tests
on:
  push:
    branches:
      - main
      - feature/*
#  pull_request:
#    branches:
#      - develop

permissions:
  contents: write

jobs:
  run-unit-tests:
    # TODO: Add the right Github Action here
    #uses: mage-os/infrastructure/.github/workflows/unit-tests.yml@main

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --no-scripts

    - name: Run unit tests
      run: vendor/bin/phpunit
